name: my
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - cloud

  kafka1:
    container_name: kafka1
    image: bitnami/kafka:3.2.1
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_HOSTS: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.121.142:9092
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - cloud
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    image: bitnami/kafka:3.2.1
    ports:
      - '9093:9092'  # 使用不同的内部端口
    environment:
      KAFKA_ZOOKEEPER_HOSTS: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.121.142:9093
      KAFKA_BROKER_ID: 2
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - cloud
    depends_on:
      - zookeeper

  kafka3:
    container_name: kafka3
    image: bitnami/kafka:3.2.1
    ports:
      - '9094:9092'  # 使用不同的内部端口
    environment:
      KAFKA_ZOOKEEPER_HOSTS: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.121.142:9094
      KAFKA_BROKER_ID: 3
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - cloud
    depends_on:
      - zookeeper

networks:
  cloud: