name: my
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - cloud

  kafka1:
    container_name: kafka1
    image: bitnami/kafka:3.8
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - cloud
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    image: bitnami/kafka:3.8
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - cloud
    depends_on:
      - zookeeper

  kafka3:
    container_name: kafka3
    image: bitnami/kafka:3.8
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - cloud
    depends_on:
      - zookeeper

networks:
  cloud: