name: my
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - cloud

  kafka1:
    container_name: kafka1
    image: bitnami/kafka:3.2.1
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.121.190:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - cloud
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    image: bitnami/kafka:3.2.1
    ports:
      - '9093:9092'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.121.190:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - cloud
    depends_on:
      - zookeeper

  kafka3:
    container_name: kafka3
    image: bitnami/kafka:3.2.1
    ports:
      - '9094:9092'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.121.190:9094
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - cloud
    depends_on:
      - zookeeper

networks:
  cloud: