name: my
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    restart: always
    networks:
      - cloud

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.8
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.121.190:9092 # 这里放当前服务器主机地址
    networks:
      - cloud
    depends_on:
      - zookeeper

networks:
  cloud: